//
// Created by sleepingmachine on 22-5-23.
//

#ifndef ABYSSAL_CV_2022_ENGINEERING_BOX_IDENTIFY_HPP
#define ABYSSAL_CV_2022_ENGINEERING_BOX_IDENTIFY_HPP

#endif //ABYSSAL_CV_2022_ENGINEERING_BOX_IDENTIFY_HPP
